#!/bin/bash
# rmv
# Just moves a file to my screenshot directory
# -------------------------------------------------------
# Author: Tama

N=0
DIR="/home/tama/images/Screenshots/"
EXT=".png"

for args in "$@"
do
    ((N++))
    M_FILE=$DIR"ss-`date '+%d-%m-%y-%H%M%S'`"$N$EXT
    mv $args $M_FILE
done
